const Router = require('koa-router')
const userInfoController = require('./../controllers/user-info')
const teamInfoController = require('./../controllers/team-info')
const pkInfoController = require('./../controllers/pk-info')
const courtInfoController = require('./../controllers/court-info')

const router = new Router()
const routers = router
    .all('/*', userInfoController.verifyToken)
    .get('/user/getUserList.json', userInfoController.getUserList)
    .get('/user/getUserInfo.json', userInfoController.getLoginUserInfo)
    .get('/user/searchUser.json', userInfoController.searchUser)
    .post('/user/signIn.json', userInfoController.signIn)
    .post('/user/signUp.json', userInfoController.signUp)
    .patch('/user/updateUserInfo.json', userInfoController.updateUserInfo)
    .post('/user/uploadHeadshot.json', userInfoController.uploadHeadshot)
    .get('/team/getTeamList.json', teamInfoController.getTeamList)
    .get('/team/getTeamInfo.json', teamInfoController.getTeamInfo)
    .post('/team/createTeam.json', teamInfoController.createTeam)
    .patch('/team/updateTeamInfo.json', teamInfoController.updateTeamInfo)
    .post('/team/uploadTeamLogo.json', teamInfoController.uploadTeamLogo)
    .delete('/team/removeTeam.json', teamInfoController.removeTeam)
    .post('/team/joinTeam.json', teamInfoController.joinTeam)
    .post('/team/outTeam.json', teamInfoController.outTeam)
    .post('/team/rejectTeam.json', teamInfoController.rejectTeam)
    .get('/player/getPlayerList.json', teamInfoController.getPlayerList)
    .get('/player/getPlayerInfo.json', teamInfoController.getPlayerInfo)
    .post('/player/createPlayer.json', teamInfoController.createPlayer)
    .patch('/player/updatePlayerInfo.json', teamInfoController.updatePlayerInfo)
    .get('/pk/getPkList.json', pkInfoController.getPkList)
    .post('/pk/createPk.json', pkInfoController.createPk)
    .patch('/pk/updatePk.json', pkInfoController.updatePk)
    .delete('/pk/removePk.json', pkInfoController.removePk)
    .post('/pk/replyPk.json', pkInfoController.replyPk)
    .get('/court/getCourtList.json', courtInfoController.getCourtList)
    .post('/court/createCourt.json', courtInfoController.createCourt)
    .patch('/court/updateCourt.json', courtInfoController.updateCourt)
    .delete('/court/removeCourt.json', courtInfoController.removeCourt)
    .post('/court/uploadCourtImg.json', courtInfoController.uploadCourtImg)


module.exports = routers